version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    ports:
      - '3001:3000'
    env_file:
      - .env.stage.docker
    depends_on:
      - db
  db:
    restart: always
    image: postgres:17.0
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env.db

volumes:
  pg_data:
